version: "3.8"

services:
  frontend:
    build:
      context: ./reactConf
      dockerfile: Dockerfile
    ports:
      - "1357:3000"
    volumes:
      - ./mon-app:/project
    command: npm run start

  backend:
    build:
      context: ./phpConf
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2345:80"
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb:10.8
    restart: always
    environment:
      MARIADB_DATABASE: gestion
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "1616:8080"