version: "3.8"

services:
  frontend:
    build:
      context: ./reactConf
      dockerfile: Dockerfile
    ports:
      - "1234:3000"
    volumes:
      - ./frontend:/project
    command: npm run start

  backend:
    build:
      context: ./phpConf
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2345:80"
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb:10.8
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-data:
